### ISSUE TITLE
showNoAlertsMsg no longer appears to work.

### ISSUE THREAD

**Issue by phot3k** [aSouchereau/MMM-CanadianPublicWeatherAlerts#4]

**Comment by aSouchereau** [comment]
Yes, looks like there was a typo where it checks the config entry's value. It's already fixed in the next update, I should be able to get it into a releasable state sometime in the next few days.

**Comment by phot3k** [comment]
Nice! Thanks for the quick response and continued efforts on the module!  I've been using it for forest fire alerts given the severity this year.
